"""empty message

Revision ID: 475fe8b778d9
Revises: 
Create Date: 2021-09-06 13:13:30.781858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475fe8b778d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ImageTest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('mimetype', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('user_pw', sa.String(length=250), nullable=False),
    sa.Column('user_name', sa.String(length=150), nullable=False),
    sa.Column('user_type', sa.String(length=100), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('permit', sa.Integer(), nullable=True),
    sa.Column('connect_date', sa.DateTime(), nullable=True),
    sa.Column('is_activate', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['Members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TestSet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('image_name', sa.String(length=300), nullable=True),
    sa.Column('image_data', sa.LargeBinary(), nullable=True),
    sa.Column('image_mimetype', sa.String(length=100), nullable=True),
    sa.Column('exam_count', sa.Integer(), nullable=True),
    sa.Column('score_open', sa.Integer(), nullable=True),
    sa.Column('test_open', sa.Integer(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['Members.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ScoreSet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('testset_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('score_sum', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('score_open', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['Members.id'], ),
    sa.ForeignKeyConstraint(['testset_id'], ['TestSet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Test2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('img_name', sa.String(length=300), nullable=True),
    sa.Column('img_file', sa.LargeBinary(), nullable=True),
    sa.Column('mimetype', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['TestSet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TestAnswer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('testset_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('file_image', sa.LargeBinary(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('mimetype', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['Members.id'], ),
    sa.ForeignKeyConstraint(['testset_id'], ['TestSet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Test_Member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('select', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['Members.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['TestSet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('AnswerSet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test2_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('score_date', sa.DateTime(), nullable=True),
    sa.Column('img_name', sa.String(length=300), nullable=True),
    sa.Column('img_file', sa.LargeBinary(), nullable=True),
    sa.Column('mimetype', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['Members.user_id'], ),
    sa.ForeignKeyConstraint(['test2_id'], ['Test2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AnswerSet')
    op.drop_table('Test_Member')
    op.drop_table('TestAnswer')
    op.drop_table('Test2')
    op.drop_table('ScoreSet')
    op.drop_table('TestSet')
    op.drop_table('Notice')
    op.drop_table('Members')
    op.drop_table('ImageTest')
    # ### end Alembic commands ###
